### ISSUE TITLE
31st of each month?

### ISSUE THREAD

**Issue by dvbn** [davidhstocker/ghcndextractor#1]
Hello @davidhstocker,

I've used this tool, it works well and is easy to use for the most part. However, I am not able to extract data for the 31st of each month. I would greatly appreciate if you can have a look at it.

When I run

``

> from ghcndextractor import ghcndextractor
> # set global filters (we will not filter by year)
> 
> ghcndextractor.countries = ["US"]
> ghcndextractor.states = ["NJ"]
> ghcndextractor.ghcnFolder = "/Users/.../ghcnd_all/"  
> ghcndextractor.readStationsFile()
> ghcndextractor.readDailyFiles()
> dayCSV = ghcndextractor.getDailyDataCSV(["10"], ["31"])

``

The output in dayCSV is 

``

> StationID, Year, Month, Day, TempMax, TempMin, Precipitation, Snowfall, SnowDepth, CloudCover(24hour), CloudCover(day)
> StationID, Year, Month, Day, TempMax, TempMin, Precipitation, Snowfall, SnowDepth, CloudCover(24hour), CloudCover(day)
> StationID, Year, Month, Day, TempMax, TempMin, Precipitation, Snowfall, SnowDepth, 

``

with no data, just lines of the variable names. Needless to say that I tested for various states and various months, this behaviour is unfortunately consistent. When I select any other day of the month, it works just fine.

I also tried to use the dailytocsv.py method, and the result is the same. Am I missing something here?

Another issue I noticed is that when you request without specifying a day (both in ghcndextractor or dailytocsv.py) you end up with a result that only contains the 30th of each month, and all other observations are lost.

Thanks a lot in advance,

DvBn

PS: I'm on Python 2.7 if that matters...

**Comment by davidhstocker** [comment]
Hi,

I'm not sure what it might be.  Perhaps I stupidly hatdcoded 30 day months
or something.  I'm undeway and can't look at it before Tuesday though.
Kind of hard to debug python on a smartphone.   I'll have a look and let
you know.  If you find the bug first, let me know.

Cheers,
Dave

**Comment by dvbn** [comment]
Hi,

I went through the code but couldn't find what the problem was - the loops seem well defined over 31 days. I won't be around a computer until Tuesday either.

Cheers,
Dv

**Comment by davidhstocker** [comment]
Hi,

I found the bug.  It seems that I was tripped up by how Python handles for
loops with ranges.

for x in range(0, 30):

The last x in the loop will be 29, not 30.  So I increased the range by 1
at lines 220 and 520 in ghcndextractor.py and that fixed it.  So now i need
to create a new tag with the patch on github and figure out how to update
the pypi entry.  ;-)

Cheers,
Dave

**Comment by dvbn** [comment]
Great @davidhstocker! Easy fix indeed. I'll remember that with python loops from now on.

However, after fixing this issue, I still have the same problem when no day in specified.

(Edit: need to increment the range by 1 at line 666, this allows to go up to day 31, though does not solve the problem below)

When I run

> dayCSV = ghcndextractor.getDailyDataCSV()

The output reads

> USC00061798, 1956, 01, 30, , , 20, , , , 
> USC00061798, 1956, 02, 30, , , , , , , 
> USC00061798, 1956, 03, 30, , , 94, , , , 

and it looks like although the script does extract all info it does not append all days into the file...

I used the following code to extract all daily data

> days = []
> alldays = []
> for x in range(1, 32):
>     days.append(str(x))
> for day in days:
>    dayCSV = ghcndextractor.getDailyDataCSV(["12"],[day],["USW00014740"])
>     alldays.extend(dayCSV)

Thanks!
Dv

**Comment by SummerQX** [comment]
@dvbn @davidhstocker 
Hi!
I change the ranges in lines 220, 520, and 666 to range(1,31).
The script is not extracting data after I put the .getDailyDataCSV() in a for loop.
Did you manage to get the weather daily data in the end?

Here is my code of the for loop, 

def dailyall(months,days,MT_list): 
    all=[]
    for st in MT_list:
        for month in months:
            for day in days:
                dayCSV = ge.getDailyDataCSV([month],[day],[st])
                all.extend(dayCSV)
    return all

#and then I use the function below to extract the data
MT_daily=dailyall(months,days,MT_list)

Are the settings of the filters here correct?

ge.countries = ['US']
ge.states=['MT']
ge.youngestYear= 1938
ge.oldestYear= 1950

Thanks!
Summer

**Comment by davidhstocker** [comment]
Hi Summer,

Your youngest year is older than your youngest year.  It uses oldest for the start of the timeslice and youngest for the end.  Without walking through a debugger, that is likely your problem.

Cheers,
Dave

**Comment by davidhstocker** [comment]
Summer's comment on the issue reminded me that I had to update the installer on PyPi.  I've incremented it to 0.2 and it includes the bugfix mentioned earlier in this thread.  I'll close the issue now.
